### ISSUE TITLE
font rendering on windows

### ISSUE THREAD

**Issue by astratagem** [templesmc/tutv#32]
particularly bad in chrome, but also in IE.

anti-aliasing.
## resources

http://www.fontspring.com/blog/smoother-web-font-rendering-chrome

**Comment by bpizzle** [comment]
How did you make this work properly on Windows again? Something about the .svg file?

**Comment by astratagem** [comment]
@bpizzle [check it out](http://paulirish.com/2009/bulletproof-font-face-implementation-syntax/)
