### ISSUE TITLE
featured videos tweaks

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tutv#43]
featured videos thumbnails aren't centered on home page (also this is happening with the clips on show pages); on other pages they box is either too large or the font too small.

**Comment by astratagem** [comment]
@bpizzle thanks. yeah i let the thumbnail regeneration run while we were out but i didn't get a chance to fix the things it broke yet. the fact that it broke is actually a good sign though! i'll work on it now (because i am lame and enjoy doing stuff like this on a friday night)

**Comment by bpizzle** [comment]
Stop bein a loser it's a Friday night! Get off github

**Comment by astratagem** [comment]
this will be addressed in #25 - merging
