### ISSUE TITLE
get rid of extra hidden nav

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tutv#61]
line 248: <div id="nav-above" class="navigation"> 
on this page http://www.templetv.net/shows/humanities-on-the-road/john-updikes-pa-with-frank-fitzpatrick/ 
it needs to go so i can have a clean report of broken links

**Comment by bpizzle** [comment]
It's still happening!!! D: 
view-source:http://www.templetv.net/shows/humanities-on-the-road/john-updikes-pa-with-frank-fitzpatrick/
search: http://www.templetv.net/behind-the-scenes-with-temple-football-ep-03/

**Comment by astratagem** [comment]
Not positive what our ultimate resolution is, but the links in `<head>` exist across the entire network of sites, caused by a particular plugin. At this point the decision goes to Todd.

**Comment by bpizzle** [comment]
well, at least we eliminated 2/3's of the hidden broken links. it's coo :100:

**Comment by astratagem** [comment]
:+1:
