### ISSUE TITLE
header nav is tweaked out

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tutv#64]
Keeps twitching upon animation of slider and tutv logo

**Comment by astratagem** [comment]
tweek.gif

**Comment by astratagem** [comment]
I actually ran into this issue on another site (I sent the link to Todd as it's relevant to our department website work), the [Commons in a Box Showcase](http://commonsinabox.org/show-case). They're using the same slider, Flexslider.

Should I look into using Royal Slider as a replacement?

**Comment by bpizzle** [comment]
but WHHHYYYYYY was it working before???
waaaahhh D;
