### ISSUE TITLE
Excerpt plugin seemingly broken for episodes on show pages

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tutv#68]
Not working on any of the episode posts, but it's fine on the home page with the blog posts, and on the schedule's episode descriptions. Very weird: 

![screen shot 2014-04-25 at 2 58 40 pm](https://cloud.githubusercontent.com/assets/4192621/2804556/a6b044a2-ccab-11e3-9446-7746f6b3d195.png)

**Comment by astratagem** [comment]
Shiiiit that's not good at all. I wonder why these problems just started happening…

As @loafintree's probably told you, I don't think I'll be in for a while. I'll try to take a look when I can. If it's happening on both your sites, it's probably affecting some other sites too…

**Comment by loafintree** [comment]
That plugin is old and unsupported. Maybe WP 3.9 finally caught up with it.

**Comment by astratagem** [comment]
I was thinking the same thing. But I didn't want it to be true. We rely so heavily on that plugin.

:unamused:

**Comment by loafintree** [comment]
Yeah. I know. I updated to 3.9 on Wednesday morning. When did it start?

**Comment by astratagem** [comment]
I think that was it. @bpizzle reported it on Temple Update yesterday: 

https://github.com/templesmc/tuupdate/issues/64

**Comment by astratagem** [comment]
Ah, but [this might be good news](http://wordpress.org/support/topic/i-was-just-curious-if-the-developer-of-this-plugin-is-continuing-to-update-it).

> the team over at Delicious Brains is taking over the project. We'll continue maintaining the plugin to ensure it functions smoothly for the foreseeable future.

**Comment by loafintree** [comment]
They had a new version 4.2. I installed and activated on TUTV. It works but I think you'll need to reset your options.

**Comment by astratagem** [comment]
Interesting, where did you find that? The plugin repo still has it at 4.1.1

**Comment by astratagem** [comment]
And by interesting, I mean that's great news.

**Comment by loafintree** [comment]
I went to Delicious Brain Github repo.
https://github.com/deliciousbrains/wp-advanced-excerpt

**Comment by astratagem** [comment]
Aha, makes sense. Looks like there are still a few issues with it, but at least we have a fix for this glaring issue. And it's good to see it's in development again. :+1: 

https://github.com/deliciousbrains/wp-advanced-excerpt/issues

**Comment by loafintree** [comment]
One problem. Because I had to update manually, it deactivated on any blogs using it so you might want to go through the ones you know and reactivate it.

**Comment by loafintree** [comment]
Ok. It's the weekend. I'm done with SMC! (for now...)

**Comment by astratagem** [comment]
Gotcha. The only one I know off the top of my head is Temple Update.

On Fri, Apr 25, 2014 at 5:59 PM, Todd M Broadbent
notifications@github.comwrote:

> One problem. Because I had to update manually, it deactivated on any blogs
> using it so you might want to go through the ones you know and reactivate
> it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/templesmc/tutv/issues/68#issuecomment-41443806
> .

## 

_Chris Montgomery_
chris@montchr.io
github.com/montchr

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
fork@temple.edu

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Vice President
Aperture Agency
apertureagency@gmail.com

_Sous les pavés, la plage_.

**Comment by astratagem** [comment]
@loafintree Enjoy! :city_sunset:

I'm going to close this for TUTV.
