### ISSUE TITLE
Add Instagram icon to homepage, etc. and link to TUTV account

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tutv#78]
![instagram-icon](https://cloud.githubusercontent.com/assets/4192621/5285060/e39b5c28-7ae6-11e4-888a-5d15db2e59eb.png)

instagram link:
http://instagram.com/temple_tv/

**Comment by astratagem** [comment]
danke

**Comment by astratagem** [comment]
Fixed in 7a7dc75dad332ce64dfc4321c5c2250e8a150b87
